"""add last_active_message_id to users

Revision ID: 33082a0d1199
Revises: f798517c235b
Create Date: 2026-07-26 08:03:50.718658

"""

from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33082a0d1199"
down_revision: Union[str, None] = "f798517c235b"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_active_message_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_active_message_id")
    # ### end Alembic commands ###
