"""sync models after main server/node changes

Revision ID: 4c3c4662aaa7
Revises: 9fa74874f586
Create Date: 2026-07-08 07:48:36.967495

"""

from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c3c4662aaa7"
down_revision: Union[str, None] = "9fa74874f586"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    op.add_column("payments", sa.Column("confirmation_url", sa.Text(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    op.drop_column("payments", "confirmation_url")
    # ### end Alembic commands ###
