"""add partial unique index for active refunds per request.

Revision ID: 8cd4052a0f89
Revises: 33082a0d1199
Create Date: 2026-08-16 01:11:56.686980

"""
from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd4052a0f89'
down_revision: Union[str, None] = '33082a0d1199'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_refunds_active_per_request', 'refunds', ['refund_request_id'], unique=True, postgresql_where=sa.text("status <> 'CANCELED' AND refund_request_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_refunds_active_per_request', table_name='refunds', postgresql_where=sa.text("status <> 'CANCELED' AND refund_request_id IS NOT NULL"))
    # ### end Alembic commands ###
