"""add support tickets and messages

Revision ID: 8e9a1f1fa6c8
Revises: 4c3c4662aaa7
Create Date: 2026-07-10 21:21:14.259955

"""

from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e9a1f1fa6c8"
down_revision: Union[str, None] = "4c3c4662aaa7"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("payment_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "REFUND",
                "TECHNICAL",
                "OTHER",
                name="support_ticket_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "IN_PROGRESS", "RESOLVED", "CLOSED", name="support_ticket_status"
            ),
            nullable=False,
        ),
        sa.Column("assigned_admin_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_admin_id"], ["admins.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_support_tickets_assigned_admin_id",
        "support_tickets",
        ["assigned_admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_tickets_payment_id"),
        "support_tickets",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        "ix_support_tickets_status", "support_tickets", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_support_tickets_subscription_id"),
        "support_tickets",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_tickets_user_id"), "support_tickets", ["user_id"], unique=False
    )
    op.create_index(
        "ix_support_tickets_user_status",
        "support_tickets",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "support_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("USER", "ADMIN", name="support_sender_type"),
            nullable=False,
        ),
        sa.Column("sender_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["support_tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_support_messages_created_at",
        "support_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_messages_ticket_id"),
        "support_messages",
        ["ticket_id"],
        unique=False,
    )
    op.execute(
        "ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'assign_support_ticket'"
    )
    op.execute(
        "ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'reply_support_ticket'"
    )
    op.execute(
        "ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'close_support_ticket'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_support_messages_ticket_id"), table_name="support_messages")
    op.drop_index("ix_support_messages_created_at", table_name="support_messages")
    op.drop_table("support_messages")
    op.drop_index("ix_support_tickets_user_status", table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_user_id"), table_name="support_tickets")
    op.drop_index(
        op.f("ix_support_tickets_subscription_id"), table_name="support_tickets"
    )
    op.drop_index("ix_support_tickets_status", table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_payment_id"), table_name="support_tickets")
    op.drop_index("ix_support_tickets_assigned_admin_id", table_name="support_tickets")
    op.drop_table("support_tickets")
    op.execute("DROP TYPE IF EXISTS support_ticket_category")
    op.execute("DROP TYPE IF EXISTS support_ticket_status")
    op.execute("DROP TYPE IF EXISTS support_sender_type")
    # ### end Alembic commands ###
