"""add webhook_events_audit

Revision ID: bb96a18f9f36
Revises: 000000000000
Create Date: 2026-07-03 04:35:34.815086

"""

from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb96a18f9f36"
down_revision: Union[str, None] = "000000000000"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_events_audit",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("old_row", sa.JSON(), nullable=True),
        sa.Column("new_row", sa.JSON(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["webhook_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_webhook_events_audit_changed_at",
        "webhook_events_audit",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_audit_event_id"),
        "webhook_events_audit",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_webhook_events_audit_event_id"), table_name="webhook_events_audit"
    )
    op.drop_index(
        "ix_webhook_events_audit_changed_at", table_name="webhook_events_audit"
    )
    op.drop_table("webhook_events_audit")
    # ### end Alembic commands ###
