"""servers node schema

Revision ID: c9abdbccf69f
Revises: 1e458f328139
Create Date: 2026-07-07 16:58:58.638318

"""

from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9abdbccf69f"
down_revision: Union[str, None] = "1e458f328139"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_payments_subscription_created_at_desc"), table_name="payments"
    )
    op.drop_index(op.f("ix_payments_user_created_at_desc"), table_name="payments")
    op.drop_index(
        op.f("ix_refund_requests_status_created_at_desc"), table_name="refund_requests"
    )
    op.add_column(
        "servers", sa.Column("marzban_node_id", sa.BigInteger(), nullable=True)
    )
    op.drop_column("servers", "api_token")
    op.drop_column("servers", "api_url")
    op.drop_index(
        op.f("ix_subscriptions_status_expires_at"), table_name="subscriptions"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_subscriptions_status_expires_at"),
        "subscriptions",
        ["status", "expires_at"],
        unique=False,
    )
    # api_url/api_token восстанавливаются как nullable=True, т.к. их реальные
    # значения были безвозвратно удалены в upgrade() через drop_column —
    # восстановить NOT NULL без backfill-данных, которых уже не существует,
    # невозможно и было бы нечестной имитацией восстановленных данных.
    op.add_column(
        "servers", sa.Column("api_url", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "servers",
        sa.Column("api_token", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("servers", "marzban_node_id")
    op.create_index(
        op.f("ix_refund_requests_status_created_at_desc"),
        "refund_requests",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_user_created_at_desc"),
        "payments",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_subscription_created_at_desc"),
        "payments",
        ["subscription_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
